           
<p align="center" class="blacktext">
<strong>
<span>
<b>
<br>
Please read the following instructions carefully
</b>
</span>
</strong>
</p>
<p class="blacktext"><strong><u>General Instructions:
</u>
</strong> 
<br>
</p>
<ol>
<li class="blacktext">Time remaining for examination is <strong><span id="times">&nbsp;<?php echo $duration ; ?></span> minutes.</strong>.</li>
<li>  The clock will be set at the server. The countdown timer in the top right corner of screen will display the remaining time available for you to complete the examination. When the timer reaches zero,
 the examination will end by itself. You will not be required to end or submit your examination.</li>  <li>  The Question Palette displayed on the right side of screen will show the status of each question using one of the following symbols:<table class="instruction_area" style="FONT-SIZE: 100%;margin-top:10px">  <tbody>  <tr style="height:40px">   <td valign="top" class="blacktext"><img src="white.jpg" width="30" height="25"></td>  <td> &nbsp;&nbsp; You have not visited the question yet.</td>  </tr>  <tr style="height:40px">   <td valign="top" class="blacktext"><img src="red.png" width="30" height="25"></td>  <td> &nbsp;&nbsp; You have not answered the question.</td>  </tr>  <tr style="height:40px">  <td valign="top" class="blacktext"><img src="green.png" width="30" height="25"></td>  <td>&nbsp;&nbsp;  You have answered the question.</td>  </tr>  <tr style="height:40px">  <td valign="top" class="blacktext"><img src="purple.png" width="30" height="25"></td> <td>&nbsp;&nbsp;  You have NOT answered the question, but have marked the question for review.</td>  </tr>  <tr style="height:40px">   <td valign="top" class="blacktext"><img src="purpletick.png" width="30" height="25"></td>  <td>&nbsp;&nbsp;  You have answered the question, but marked it for review.</td>  </tr>  </tbody>  </table>  The Marked for Review status for a question simply indicates that you would like to look at that question again.<span style="color:#ff0000;"> If a question is answered and Marked for Review, your answer for that question will be considered in the evaluation.</span></li>  <li>  You can click on the "&gt;" arrow which appears to the left of question palette to collapse the question palette thereby maximizing the question window. To view the question palette again, you can click on "&lt;" which appears on the right side of question window.</li>
<p>  <br>  <b><u>Navigating to a Question : </u></b></p> <ol start="5" style="TEXT-ALIGN: left; LIST-STYLE-TYPE: decimal; PADDING-LEFT: 4%; PADDING-TOP: 3px">  <li>  To answer a question, do the following:  <ol style="TEXT-ALIGN: left; PADDING-LEFT: 4%; PADDING-TOP: 3px" type="a">  <li>  Click on the question number in the Question Palette at the right of your screen to go to that numbered question directly. Note that using this option does NOT save your answer to the current question.</li>  <li>  Click on <strong>Save &amp;Next</strong> to save your answer for the current question and then go to the next question.</li>  <li>  Click on <strong>Mark for Review &amp; Next </strong>to save your answer for the current question, mark it for review, and then go to the next question.</li>  </ol>  </li> </ol> <p>  <br>  <b><u>Answering a Question : </u></b></p> <ol start="6" style="TEXT-ALIGN: left; LIST-STYLE-TYPE: decimal; PADDING-LEFT: 4%; PADDING-TOP: 3px">  <li>  Procedure for answering a multiple choice type question:  <ol style="TEXT-ALIGN: left; PADDING-LEFT: 4%; PADDING-TOP: 3px" type="a">  <li>  To select your answer, click on the button of one of the options</li>  <li>  To deselect your chosen answer, click on the button of the chosen option again or click on the <b>Clear Response</b> button</li>  <li>  To change your chosen answer, click on the button of another option</li>  <li>  To save your answer, you MUST click on the <b>Save &amp; Next</b> button</li>  <li>  To mark the question for review, click on the <b>Mark for Review &amp; Next</b> button.If an answer is selected for a question that is Marked for Review, that answer will be considered in the evaluation.</li>  </ol>  </li>  <li>  To change your answer to a question that has already been answered, first select that question for answering and then follow the procedure for answering that type of question.</li>  <li>  Note that ONLY Questions for which answers are saved or marked for review after answering will be considered for evaluation.</li> </ol> <p>  <br>  <b><u>Navigating through sections: </u></b></p> <ol start="9" style="TEXT-ALIGN: left; LIST-STYLE-TYPE: decimal; PADDING-LEFT: 4%; PADDING-TOP: 3px"> <?php if($time_limit == 0) { ?> <li>  Sections in this question paper are displayed on the top bar of the screen. Questions in a section can be viewed by clicking on the section name. The section you are currently viewing is highlighted.</li>  <li>  After clicking the Save &amp; Next button on the last question for a section, you will automatically be taken to the first question of the next section.</li>  <li>  You can shuffle between tests and questions anytime during the examination as per your convenience only during the time stipulated.</li>  <li>  Candidate can view the corresponding section summary as part of the legend that appears in every section above the question palette.</li> <?php } ?>
<?php if($time_limit == 1) { ?> <li>  Sections in this question paper are displayed on the top bar of the screen. At a time only 1 section can be viewed</li>  <li>  After clicking the Save &amp; Next button on the last question for a section, you will automatically be taken to the first question of the that section.</li>  <li>  You cannot shuffle between tests and questions during the examination </li>  <li>  Candidate can view the corresponding section summary as part of the legend that appears in every section above the question palette.</li> <?php } ?>
 </ol>			   
			   		   
<!-- <li class="blacktext">You will be awarded three marks for each correct answer.</li> -->
<!-- <li class="blacktext">Each wrong answer will attract a penalty of one mark.</li> -->
			 </ol>